name: Build Dev Branch and Push Docker Image to Azure

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: Login to Azure Registry
        uses: azure/docker-login@v1
        with:
          login-server: itisdev.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push
        working-directory: ./
        run: |
          docker build . -t itisdev.azurecr.io/dev:latest
          docker push itisdev.azurecr.io/dev:latest
